### ISSUE TITLE
how to generate instructions

### ISSUE THREAD

**Issue by caichuang0415** [DCDmllm/WorldGPT#2]
Thanks for sharing your codes.
In your readme file, I understood how to generate image or video based on inputs. But how to generate texts?
In some cases, I will make the input contains a image and a description of this image, and I want the model output a list texts like this pictures in your paper shows:
![a](https://github.com/DCDmllm/WorldGPT/assets/50684798/5d87ef68-4b46-493c-a17f-c3a4ba2e64eb)
Hope for your reply, thanks

**Comment by WestbrookGE** [comment]
Absolutely! Here's a reply you could use on GitHub, balancing clarity with technical detail:

**Reply:**

Hi @caichuang0415, 

Thanks for your question and for checking out our code!

You're right, our README focuses on multimodal generation leveraging WorldGPT. The text generation part is a bit different and was a key part of our research process.  Here's a quick summary:

1. **Seed Instructions:** We started with a set of manually collected instructions that combined both text descriptions and multimodal parts. These were our initial examples.

2. **GPT-4 Expansion:** We leveraged GPT-4's capabilities to generate more textual instructions based on those seed examples (with text part inputs only). This helped us create a much larger dataset of text-based instructions.

3. **WorldGPT Completion:** Finally, our WorldGPT model took these expanded text instructions and generated the corresponding multimodal outputs (images, videos, audios) to complete the multimodal dataset.

**More Info:**

For a detailed breakdown of our instruction generation process, definitely check out Section 6 of our paper. It explains the intricacies of this step.

Let me know if you have any other questions!

**Comment by caichuang0415** [comment]
> Absolutely! Here's a reply you could use on GitHub, balancing clarity with technical detail:
> 
> **Reply:**
> 
> Hi @caichuang0415,
> 
> Thanks for your question and for checking out our code!
> 
> You're right, our README focuses on multimodal generation leveraging WorldGPT. The text generation part is a bit different and was a key part of our research process. Here's a quick summary:
> 
> 1. **Seed Instructions:** We started with a set of manually collected instructions that combined both text descriptions and multimodal parts. These were our initial examples.
> 2. **GPT-4 Expansion:** We leveraged GPT-4's capabilities to generate more textual instructions based on those seed examples (with text part inputs only). This helped us create a much larger dataset of text-based instructions.
> 3. **WorldGPT Completion:** Finally, our WorldGPT model took these expanded text instructions and generated the corresponding multimodal outputs (images, videos, audios) to complete the multimodal dataset.
> 
> **More Info:**
> 
> For a detailed breakdown of our instruction generation process, definitely check out Section 6 of our paper. It explains the intricacies of this step.
> 
> Let me know if you have any other questions!

thanks for your detailed answer. I understand your expalanation of the instruction generate procedure and I will read more in your paper. thank you
